- type: pointOfInterest
  id: BasePOI
  abstract: true
  minimumDistance: 1000 # Some sane defaults
  maximumDistance: 2500
  spawnGamePreset: [ NFAdventure, NFPirate ]
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#dcfff7"
    readOnly: true
  # Prevent gravity changes
  - type: ForceAnchor
