- type: department
  id: Frontier
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - StationRepresentative
  - StationTrafficController
  - Valet # nyano
  - MailCarrier # nyano
  - SecurityGuard

# - type: department
#   id: Antag
#   name: department-Antag
#   description: department-NFAntag-description
#   color: "#311313"
#   weight: -20 # accounted for in jobs
#   roles:
#   - NFPirateCaptain
#   - NFPirateFirstMate
#   - NFPirate
#   - Prisoner #nyano
